baseURL = "https://www.hmeyerohle.me"
title = "Hendrik Meyer-Ohle"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy; 2024, Hendrik Meyer-Ohle"

# Main menu items
[menu]
[[menu.main]]
identifier = "about"
name = "About"
title = "About"
url = "/about/"
weight = -110
#[[menu.main]]
#identifier = "posts"
#name = "Posts"
#title = "Posts"
#url = "/post/"
#weight = -100
[[menu.main]]
identifier = "current-research"
name = "Current Research"
title = "Current Research"
url = "/current_research/"
weight = -90
[[menu.main]]
identifier = "previous-research"
name = "Previous Research"
title = "Previous Research"
url = "/previous_research/"
weight = -90

# Configuration Features
[params]
description = "Your meta description"      # Your meta description of the site
header_title = "Dr. Hendrik Meyer-Ohle"                 # Your header title
header_subtitle = "Associate Professor" # Your header subtitle
home_image = "/images/me.avif"          # Path to header image starting from the static directory
#recent_posts = 5                           # Max amount of recent posts to show
#mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
[params.style]                             # CSS style overrides
backgroundColor = "#f8f9fa"
fontColor = "#212529"
[[params.social]]
fa_icon = "fab fa-linkedin-in fa-1x"
href = "https://www.linkedin.com/in/hendrik-meyer-ohle-3522707b/"
[[params.social]]
fa_icon = "fab fa-researchgate fa-1x"
href = "https://www.researchgate.net/profile/Hendrik-Meyer-Ohle"
[[params.social]]
fa_icon = "fas fa-envelope fa-1x"
href = "mailto:me@hmeyerohle.me"